In [32]:
import pandas as pd
import numpy as np

In [33]:
dfene = pd.read_csv("../input/sales_2017_enero.csv")

In [34]:
dfene

                id        date  store_nbr  item_nbr  unit_sales  onpromotion
0        101688779  2017-01-01         25     99197         1.0        False
1        101688780  2017-01-01         25    103665         7.0        False
2        101688781  2017-01-01         25    105574         1.0        False
3        101688782  2017-01-01         25    105857         4.0        False
4        101688783  2017-01-01         25    106716         2.0        False
...            ...         ...        ...       ...         ...          ...
3134765  104823544  2017-01-31         54   2048300         3.0        False
3134766  104823545  2017-01-31         54   2048313         3.0        False
3134767  104823546  2017-01-31         54   2048421         5.0        False
3134768  104823547  2017-01-31         54   2048471         4.0        False
3134769  104823548  2017-01-31         54   2048515         2.0        False

[3134770 rows x 6 columns]

In [35]:
dfene.dtypes

id               int64
date            object
store_nbr        int64
item_nbr         int64
unit_sales     float64
onpromotion       bool
dtype: object

In [36]:
dfene["date"] = pd.to_datetime(dfene.date)

In [37]:
dfene.dtypes

id                      int64
date           datetime64[ns]
store_nbr               int64
item_nbr                int64
unit_sales            float64
onpromotion              bool
dtype: object

In [38]:
stores = pd.read_csv("../input/stores.csv")

In [39]:
stores

    store_nbr           city                           state type  cluster
0           1          Quito                       Pichincha    D       13
1           2          Quito                       Pichincha    D       13
2           3          Quito                       Pichincha    D        8
3           4          Quito                       Pichincha    D        9
4           5  Santo Domingo  Santo Domingo de los Tsachilas    D        4
5           6          Quito                       Pichincha    D       13
6           7          Quito                       Pichincha    D        8
7           8          Quito                       Pichincha    D        8
8           9          Quito                       Pichincha    B        6
9          10          Quito                       Pichincha    C       15
10         11        Cayambe                       Pichincha    B        6
11         12      Latacunga                        Cotopaxi    C       15
12         13      Latacunga                        Cotopaxi    C       15
13         14       Riobamba                      Chimborazo    C        7
14         15         Ibarra                        Imbabura    C       15
15         16  Santo Domingo  Santo Domingo de los Tsachilas    C        3
16         17          Quito                       Pichincha    C       12
17         18          Quito                       Pichincha    B       16
18         19       Guaranda                         Bolivar    C       15
19         20          Quito                       Pichincha    B        6
20         21  Santo Domingo  Santo Domingo de los Tsachilas    B        6
21         22           Puyo                         Pastaza    C        7
22         23         Ambato                      Tungurahua    D        9
23         24      Guayaquil                          Guayas    D        1
24         25        Salinas                     Santa Elena    D        1
25         26      Guayaquil                          Guayas    D       10
26         27          Daule                          Guayas    D        1
27         28      Guayaquil                          Guayas    E       10
28         29      Guayaquil                          Guayas    E       10
29         30      Guayaquil                          Guayas    C        3
30         31       Babahoyo                        Los Rios    B       10
31         32      Guayaquil                          Guayas    C        3
32         33        Quevedo                        Los Rios    C        3
33         34      Guayaquil                          Guayas    B        6
34         35         Playas                          Guayas    C        3
35         36       Libertad                          Guayas    E       10
36         37         Cuenca                           Azuay    D        2
37         38           Loja                            Loja    D        4
38         39         Cuenca                           Azuay    B        6
39         40        Machala                          El Oro    C        3
40         41        Machala                          El Oro    D        4
41         42         Cuenca                           Azuay    D        2
42         43     Esmeraldas                      Esmeraldas    E       10
43         44          Quito                       Pichincha    A        5
44         45          Quito                       Pichincha    A       11
45         46          Quito                       Pichincha    A       14
46         47          Quito                       Pichincha    A       14
47         48          Quito                       Pichincha    A       14
48         49          Quito                       Pichincha    A       11
49         50         Ambato                      Tungurahua    A       14
50         51      Guayaquil                          Guayas    A       17
51         52          Manta                          Manabi    A       11
52         53          Manta                          Manabi    D       13
53         54      El Carmen                          Manabi    C        3

In [40]:
dfm = dfene.merge(stores, on="store_nbr")

In [41]:
pd.pivot_table(data = dfm, values = "unit_sales", index = "city", columns = "item_nbr", aggfunc = "sum").fillna(0)

item_nbr,99197,103501,103520,103665,105574,105575,105576,105577,105693,105737,...,2048633,2048674,2048874,2049037,2049153,2054101,2054291,2056549,2057231,2058907
city,,,,,,,,,,,,,,,,,,,,,
Ambato,16.0,0.0,104.0,98.0,343.0,988.0,0.0,112.0,73.0,196.0,...,232.0,0.0,8.0,44.0,59.0,275.0,120.0,0.0,782.721,10.0
Babahoyo,0.0,174.0,24.0,93.0,0.0,0.0,385.0,0.0,81.0,0.0,...,45.0,162.0,0.0,0.0,0.0,0.0,34.0,0.0,34.837,0.0
Cayambe,0.0,152.0,16.0,48.0,0.0,0.0,539.0,0.0,20.0,0.0,...,27.0,116.0,0.0,0.0,0.0,0.0,0.0,1022.0,279.402,0.0
Cuenca,58.0,175.0,212.0,281.0,609.0,954.0,441.0,136.0,71.0,120.0,...,153.0,36.0,5.0,22.0,79.0,277.0,160.0,248.0,1393.163,16.0
Daule,20.0,0.0,0.0,112.0,85.0,157.0,0.0,52.0,61.0,322.0,...,154.0,0.0,0.0,6.0,6.0,1.0,7.0,0.0,361.661,14.0
El Carmen,0.0,119.0,26.0,0.0,0.0,0.0,413.0,0.0,95.0,0.0,...,0.0,362.0,0.0,12.0,6.0,0.0,11.0,0.0,0.000,0.0
Esmeraldas,0.0,163.0,35.0,42.0,0.0,0.0,411.0,0.0,63.0,0.0,...,77.0,786.0,0.0,0.0,4.0,0.0,0.0,716.0,144.889,0.0
Guaranda,0.0,117.0,48.0,0.0,0.0,0.0,482.0,0.0,5.0,0.0,...,0.0,375.0,0.0,0.0,0.0,0.0,65.0,0.0,0.000,0.0
Guayaquil,103.0,752.0,204.0,498.0,822.0,735.0,1465.0,81.0,521.0,721.0,...,567.0,1128.0,7.0,103.0,106.0,356.0,312.0,195.0,2164.241,32.0
Ibarra,0.0,139.0,19.0,120.0,0.0,0.0,337.0,0.0,23.0,0.0,...,0.0,169.0,0.0,2.0,16.0,0.0,9.0,0.0,0.000,0.0
Latacunga,0.0,192.0,27.0,0.0,0.0,0.0,470.0,0.0,40.0,0.0,...,0.0,268.0,0.0,0.0,2.0,72.0,39.0,0.0,0.000,0.0
Libertad,0.0,137.0,3.0,58.0,0.0,0.0,360.0,0.0,34.0,0.0,...,132.0,399.0,0.0,3.0,0.0,113.0,74.0,0.0,57.252,0.0
Loja,49.0,0.0,64.0,71.0,167.0,812.0,0.0,415.0,45.0,97.0,...,30.0,0.0,0.0,0.0,22.0,0.0,1.0,0.0,658.201,0.0
Machala,21.0,229.0,87.0,72.0,84.0,178.0,533.0,740.0,211.0,40.0,...,62.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,266.863,17.0
Manta,3.0,0.0,70.0,28.0,419.0,198.0,0.0,17.0,55.0,166.0,...,92.0,0.0,0.0,19.0,28.0,0.0,9.0,0.0,195.141,0.0
Playas,0.0,69.0,0.0,0.0,0.0,0.0,66.0,0.0,12.0,0.0,...,0.0,265.0,0.0,8.0,0.0,22.0,10.0,0.0,0.000,0.0
Puyo,0.0,103.0,21.0,0.0,0.0,0.0,317.0,0.0,19.0,0.0,...,0.0,14.0,0.0,0.0,0.0,18.0,0.0,0.0,0.000,0.0
Quevedo,0.0,130.0,14.0,0.0,0.0,0.0,422.0,0.0,32.0,0.0,...,0.0,0.0,0.0,11.0,7.0,0.0,0.0,0.0,0.000,0.0
Quito,722.0,713.0,1289.0,1705.0,6091.0,10127.0,2917.0,1584.0,672.0,2111.0,...,3410.0,694.0,116.0,290.0,270.0,3912.0,1630.0,774.0,18157.680,113.0
Riobamba,0.0,127.0,55.0,0.0,0.0,0.0,427.0,0.0,48.0,0.0,...,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.000,0.0
Salinas,32.0,0.0,20.0,58.0,57.0,106.0,0.0,12.0,1.0,119.0,...,137.0,0.0,0.0,17.0,3.0,0.0,0.0,0.0,298.853,0.0
Santo Domingo,0.0,199.0,69.0,158.0,184.0,348.0,662.0,166.0,190.0,84.0,...,46.0,187.0,0.0,19.0,39.0,191.0,229.0,1584.0,240.706,11.0

In [42]:
dfm["dayname"] = dfm.date.dt.day_name(locale="es.utf8")

In [43]:
dfg = dfm.groupby("city")["unit_sales"].sum().reset_index()

In [44]:
dfg.columns = ["ciudad","total"]

In [45]:
ser = dfm.groupby("city")["unit_sales"].sum()

In [46]:
ser.idxmax()

'Quito'

In [47]:
ser.max()

13884404.043

In [48]:
ser.min()

169535.914

In [49]:
ser.describe()

count    2.200000e+01
mean     1.196733e+06
std      2.897105e+06
min      1.695359e+05
25%      2.734627e+05
50%      4.079314e+05
75%      7.721713e+05
max      1.388440e+07
Name: unit_sales, dtype: float64

In [50]:
ser2 = dfm.groupby(["state","city"])["unit_sales"].size()

In [51]:
ser2.reset_index()

                             state           city  unit_sales
0                            Azuay         Cuenca      195012
1                          Bolivar       Guaranda       44185
2                       Chimborazo       Riobamba       43434
3                         Cotopaxi      Latacunga       85805
4                           El Oro        Machala      111513
5                       Esmeraldas     Esmeraldas       55060
6                           Guayas          Daule       62873
7                           Guayas      Guayaquil      419011
8                           Guayas       Libertad       54796
9                           Guayas         Playas       32844
10                        Imbabura         Ibarra       46720
11                            Loja           Loja       63689
12                        Los Rios       Babahoyo       56183
13                        Los Rios        Quevedo       45402
14                          Manabi      El Carmen       39517
15                          Manabi          Manta       60550
16                         Pastaza           Puyo       43387
17                       Pichincha        Cayambe       61040
18                       Pichincha          Quito     1270673
19                     Santa Elena        Salinas       53518
20  Santo Domingo de los Tsachilas  Santo Domingo      158635
21                      Tungurahua         Ambato      130923

In [52]:
dfr = dfm.groupby("city").agg({"unit_sales":["min","max","mean","size"]})

In [53]:
dfr = dfr.reset_index()

In [54]:
dfr.columns = dfr.columns.droplevel()

dfr.colums = ["city","min","max","promedio","cantidad"]

In [55]:
dfr

                       min       max       mean     size
0          Ambato   -1.034  1598.000   7.209263   130923
1        Babahoyo -336.000  1129.000   7.076803    56183
2         Cayambe  -20.000   578.333   9.722268    61040
3          Cuenca   -3.000  2569.000   7.169440   195012
4           Daule   -6.000   569.000   7.844890    62873
5       El Carmen   -1.000  2582.000   6.438827    39517
6      Esmeraldas  -18.000   553.000   7.733022    55060
7        Guaranda  -42.000   389.938   6.112945    44185
8       Guayaquil  -47.000  5750.000   7.006095   419011
9          Ibarra   -1.000   398.000   5.339824    46720
10      Latacunga   -1.435   532.302   5.116497    85805
11       Libertad  -10.323   304.000   6.500527    54796
12           Loja   -1.000  1850.000   6.567330    63689
13        Machala   -4.000  2891.000   7.458736   111513
14          Manta   -1.000   541.000   6.134051    60550
15         Playas    0.088   417.000   5.161853    32844
16           Puyo   -2.000   281.000   4.395486    43387
17        Quevedo  -61.000  4651.000   6.713928    45402
18          Quito -290.000  2997.000  10.926811  1270673
19       Riobamba   -5.000   543.000   5.503351    43434
20        Salinas  -14.000   735.000   5.298203    53518
21  Santo Domingo   -4.769   708.000   5.532950   158635

In [56]:
tabla2 = pd.pivot_table(data = dfm, values = "unit_sales", index = "city", columns = "dayname", aggfunc = "sum").fillna(0)

In [57]:
tabla2 = tabla2.iloc[:,[2,3,4,1,-1,-2,0]]

In [58]:
tabla2

dayname,Lunes,Martes,MiÃ£Â©rcoles,Jueves,Viernes,SÃ£Â¡bado,Domingo
city,,,,,,,
Ambato,166863.491,140735.930,111360.829,96362.013,112809.585,152308.313,163418.167
Babahoyo,68174.344,71098.934,41258.451,43179.309,41429.855,61127.389,71327.759
Cayambe,104763.652,100256.629,72137.457,63297.769,63065.598,86073.297,103852.830
Cuenca,240912.924,222784.773,191293.166,144806.051,164248.108,224358.020,209723.780
Daule,82848.597,75378.228,67193.303,47477.694,54480.472,72235.791,93617.695
El Carmen,48587.852,41888.719,30085.535,23812.035,26403.818,37047.706,46617.470
Esmeraldas,75081.792,79359.812,48633.021,47272.745,45711.717,58224.391,71496.731
Guaranda,48685.908,42998.583,31254.763,26502.505,27834.742,53225.244,39598.749
Guayaquil,475696.956,515607.225,383902.146,301277.985,367596.164,417215.980,474334.592
Ibarra,46651.025,45033.876,32324.244,28896.106,28117.381,35116.368,33337.588
Latacunga,81897.103,73805.608,53305.788,48696.940,48293.296,69677.884,63344.399
Libertad,61039.326,73992.698,40803.263,38729.589,39683.622,49090.194,52864.163
Loja,68527.955,56198.639,60167.664,36280.082,48156.001,76077.452,72858.874
Machala,143720.372,143070.808,111285.730,87940.609,91894.310,124701.638,129132.552
Manta,59926.278,53321.446,51559.417,34841.604,42321.868,58188.171,71257.976
Playas,32542.369,30311.993,17520.326,17334.934,19280.998,26319.211,26226.083
Puyo,35763.005,32425.187,24289.085,20653.372,19976.040,27541.488,30058.789
Quevedo,49630.657,62138.168,35117.063,31801.740,29750.944,45832.702,50554.480
Quito,2380998.208,2011691.945,1713322.333,1307677.669,1623088.188,2274526.188,2573099.512
Riobamba,42901.373,41830.739,28480.156,27918.249,25262.399,42699.158,29940.453
Salinas,40721.873,35116.637,36763.993,26784.886,44308.872,53980.483,45872.475
Santo Domingo,160802.254,148300.676,105777.038,89178.144,92602.854,129861.898,151196.653