In [2]:
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point

In [3]:
gdf = gpd.read_file("../input/parroquias.geojson")

In [4]:
df = pd.read_csv("../output/data.csv")

In [5]:
df

,antigüedad,cuartos,cuartosdebaño,estacionamiento,metroscuadradostotales,precio,publicado,tipodevendedor,titulo,lat,long
0,5,4,4,0,480,565000,NaN,NaN,Arrecife - Punta Mocoli Design By Jannina Cabal,-2.115345,-79.856163
1,20,4,4,3,244,140000,NaN,NaN,Venta de Casa Cdla. del Biess Remodelada - Sec...,-2.230328,-79.902163
2,En construcción,0,4,2,1,259000,NaN,NaN,Se Vende Proyecto en Isla Celeste Reserva Solo...,-2.071614,-79.842065
3,A estrenar,4,4,0,245,245000,NaN,NaN,Isla Celeste 243 m² Const y 225 m² Terreno Her...,-2.079416,-79.837993
4,A estrenar,0,4,2,1090,650000,NaN,NaN,"Casa 1 Planta Al Lago - 4 D - $650,000",-2.142226,-79.864596
...,...,...,...,...,...,...,...,...,...,...,...
2284,NaN,0,1,3,233,250000,NaN,NaN,Casa Esquinera en La Puntilla,-2.229309,-79.935185
2285,10,4,6,4,670,298000,NaN,NaN,Vendo Casa Cdla. Santa Cecilia Via a La Costa ...,-2.162710,-79.941728
2286,5,3,3,2,250,270000,NaN,NaN,Vendo Linda Casa en Los Primeros Kms de Sambor...,-2.140583,-79.868761
2287,4,3,2,1,136,120000,NaN,NaN,"Venta Casa en Urb. Villa Club, etapa Jupiter, ...",-2.028782,-79.895465
2288,6,3,4,2,350,380000,NaN,NaN,Oportunidad Moderna Casa en Via a La Costa Urb...,-2.195229,-80.053084

In [6]:
Q1 = df['precio'].quantile(0.25)
Q3 = df['precio'].quantile(0.75)
IQR = Q3 - Q1

In [7]:
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

In [8]:
df = df.loc[(df['precio'] >= limite_inferior)&(df['precio'] <= limite_superior),:]

In [9]:
df

,antigüedad,cuartos,cuartosdebaño,estacionamiento,metroscuadradostotales,precio,publicado,tipodevendedor,titulo,lat,long
0,5,4,4,0,480,565000,NaN,NaN,Arrecife - Punta Mocoli Design By Jannina Cabal,-2.115345,-79.856163
1,20,4,4,3,244,140000,NaN,NaN,Venta de Casa Cdla. del Biess Remodelada - Sec...,-2.230328,-79.902163
2,En construcción,0,4,2,1,259000,NaN,NaN,Se Vende Proyecto en Isla Celeste Reserva Solo...,-2.071614,-79.842065
3,A estrenar,4,4,0,245,245000,NaN,NaN,Isla Celeste 243 m² Const y 225 m² Terreno Her...,-2.079416,-79.837993
4,A estrenar,0,4,2,1090,650000,NaN,NaN,"Casa 1 Planta Al Lago - 4 D - $650,000",-2.142226,-79.864596
...,...,...,...,...,...,...,...,...,...,...,...
2284,NaN,0,1,3,233,250000,NaN,NaN,Casa Esquinera en La Puntilla,-2.229309,-79.935185
2285,10,4,6,4,670,298000,NaN,NaN,Vendo Casa Cdla. Santa Cecilia Via a La Costa ...,-2.162710,-79.941728
2286,5,3,3,2,250,270000,NaN,NaN,Vendo Linda Casa en Los Primeros Kms de Sambor...,-2.140583,-79.868761
2287,4,3,2,1,136,120000,NaN,NaN,"Venta Casa en Urb. Villa Club, etapa Jupiter, ...",-2.028782,-79.895465
2288,6,3,4,2,350,380000,NaN,NaN,Oportunidad Moderna Casa en Via a La Costa Urb...,-2.195229,-80.053084

In [10]:
df.drop_duplicates(subset=["metroscuadradostotales","lat","long"], keep="last", inplace = True)
df.dropna(subset=["metroscuadradostotales","precio","lat","long"],inplace=True)
df = df.loc[df["metroscuadradostotales"]>0,:]
df["preciopmt2"] = df["precio"] / df["metroscuadradostotales"]

C:\Users\sebastian\AppData\Local\Temp\ipykernel_15180\1817488069.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(subset=["metroscuadradostotales","lat","long"], keep="last", inplace = True)
C:\Users\sebastian\AppData\Local\Temp\ipykernel_15180\1817488069.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=["metroscuadradostotales","precio","lat","long"],inplace=True)
C:\Users\sebastian\AppData\Local\Temp\ipykernel_15180\1817488069.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["preciopmt2"] = df["precio"] / df["metroscuadradostotales"]

In [11]:
df

,antigüedad,cuartos,cuartosdebaño,estacionamiento,metroscuadradostotales,precio,publicado,tipodevendedor,titulo,lat,long,preciopmt2
0,5,4,4,0,480,565000,NaN,NaN,Arrecife - Punta Mocoli Design By Jannina Cabal,-2.115345,-79.856163,1177.083333
1,20,4,4,3,244,140000,NaN,NaN,Venta de Casa Cdla. del Biess Remodelada - Sec...,-2.230328,-79.902163,573.770492
2,En construcción,0,4,2,1,259000,NaN,NaN,Se Vende Proyecto en Isla Celeste Reserva Solo...,-2.071614,-79.842065,259000.000000
3,A estrenar,4,4,0,245,245000,NaN,NaN,Isla Celeste 243 m² Const y 225 m² Terreno Her...,-2.079416,-79.837993,1000.000000
4,A estrenar,0,4,2,1090,650000,NaN,NaN,"Casa 1 Planta Al Lago - 4 D - $650,000",-2.142226,-79.864596,596.330275
...,...,...,...,...,...,...,...,...,...,...,...,...
2284,NaN,0,1,3,233,250000,NaN,NaN,Casa Esquinera en La Puntilla,-2.229309,-79.935185,1072.961373
2285,10,4,6,4,670,298000,NaN,NaN,Vendo Casa Cdla. Santa Cecilia Via a La Costa ...,-2.162710,-79.941728,444.776119
2286,5,3,3,2,250,270000,NaN,NaN,Vendo Linda Casa en Los Primeros Kms de Sambor...,-2.140583,-79.868761,1080.000000
2287,4,3,2,1,136,120000,NaN,NaN,"Venta Casa en Urb. Villa Club, etapa Jupiter, ...",-2.028782,-79.895465,882.352941
2288,6,3,4,2,350,380000,NaN,NaN,Oportunidad Moderna Casa en Via a La Costa Urb...,-2.195229,-80.053084,1085.714286

In [12]:
gcasas = gpd.GeoDataFrame(df,geometry= gpd.points_from_xy(df["long"],df["lat"]))

In [13]:
gcasas.crs = gdf.crs
gjoin = gpd.sjoin(gcasas,gdf)
grouped = gjoin.groupby('Name').agg({
    'precio': 'mean',  
    'preciopmt2': 'mean',
    'geometry': lambda x: x.unary_union.centroid  
}).reset_index()
gdfR = gpd.GeoDataFrame(grouped, geometry='geometry')

In [14]:
gdfR

,Name,precio,preciopmt2,geometry
0,Parroquia Ayacucho,317500.000000,513.477959,POINT (-79.89223 -2.21147)
1,Parroquia Bolivar,161750.000000,561.030655,POINT (-79.88980 -2.20337)
2,Parroquia Febres Cordero,290376.541667,848.266543,POINT (-79.92411 -2.21076)
3,Parroquia Garcia Moreno,99500.000000,406.029433,POINT (-79.90077 -2.21711)
4,Parroquia Letamendi,94714.285714,515.921676,POINT (-79.91039 -2.20687)
5,Parroquia Nueve de Octubre,247500.000000,952.997923,POINT (-79.89225 -2.18817)
6,Parroquia Olmedo,97500.000000,832.634102,POINT (-79.88606 -2.20356)
7,Parroquia Pascuales,143052.631579,775.167247,POINT (-79.93337 -2.07292)
8,Parroquia Pedro Carbo,146545.454545,757.572619,POINT (-79.88159 -2.19153)
9,Parroquia Roca,184200.000000,798.733836,POINT (-79.88689 -2.18829)
10,Parroquia Rocafuerte,224545.454545,890.276285,POINT (-79.88714 -2.19227)
11,Parroquia Sucre,165357.142857,584.299994,POINT (-79.89638 -2.20090)
12,Parroquia Tarqui,229226.959147,796.947124,POINT (-79.91300 -2.14136)
13,Parroquia Urdaneta,163818.181818,4409.875793,POINT (-79.90744 -2.19712)
14,Parroquia Ximena,151705.882353,533.076131,POINT (-79.89582 -2.23884)
15,Parroquia de Chongon,292777.184211,2332.998355,POINT (-79.96709 -2.18904)

In [15]:
gdfR.set_crs(epsg=4326, inplace=True)

,Name,precio,preciopmt2,geometry
0,Parroquia Ayacucho,317500.000000,513.477959,POINT (-79.89223 -2.21147)
1,Parroquia Bolivar,161750.000000,561.030655,POINT (-79.88980 -2.20337)
2,Parroquia Febres Cordero,290376.541667,848.266543,POINT (-79.92411 -2.21076)
3,Parroquia Garcia Moreno,99500.000000,406.029433,POINT (-79.90077 -2.21711)
4,Parroquia Letamendi,94714.285714,515.921676,POINT (-79.91039 -2.20687)
5,Parroquia Nueve de Octubre,247500.000000,952.997923,POINT (-79.89225 -2.18817)
6,Parroquia Olmedo,97500.000000,832.634102,POINT (-79.88606 -2.20356)
7,Parroquia Pascuales,143052.631579,775.167247,POINT (-79.93337 -2.07292)
8,Parroquia Pedro Carbo,146545.454545,757.572619,POINT (-79.88159 -2.19153)
9,Parroquia Roca,184200.000000,798.733836,POINT (-79.88689 -2.18829)
10,Parroquia Rocafuerte,224545.454545,890.276285,POINT (-79.88714 -2.19227)
11,Parroquia Sucre,165357.142857,584.299994,POINT (-79.89638 -2.20090)
12,Parroquia Tarqui,229226.959147,796.947124,POINT (-79.91300 -2.14136)
13,Parroquia Urdaneta,163818.181818,4409.875793,POINT (-79.90744 -2.19712)
14,Parroquia Ximena,151705.882353,533.076131,POINT (-79.89582 -2.23884)
15,Parroquia de Chongon,292777.184211,2332.998355,POINT (-79.96709 -2.18904)

In [16]:
gdfR.to_file("data.geojson", driver='GeoJSON')